"""Eight-week post-bootcamp Salesforce interview-readiness curriculum."""

RUBRIC = [
    {
        "key": "business",
        "label": "Business and requirement understanding",
        "max_score": 20,
        "description": "Identifies the real business problem, users, constraints, scope, and success criteria.",
    },
    {
        "key": "evidence",
        "label": "Evidence and reasoning",
        "max_score": 20,
        "description": "Uses specific examples, credible sources, comparisons, and defensible reasoning.",
    },
    {
        "key": "salesforce",
        "label": "Salesforce application",
        "max_score": 20,
        "description": "Connects the need to appropriate data, security, automation, integration, testing, and platform choices.",
    },
    {
        "key": "communication",
        "label": "Communication and interview delivery",
        "max_score": 20,
        "description": "Explains decisions clearly, directly, and in a structure an interviewer can follow.",
    },
    {
        "key": "professionalism",
        "label": "Completeness and professionalism",
        "max_score": 20,
        "description": "Submits complete, organized, accurate work and responds thoughtfully to feedback.",
    },
]


def step(title, purpose, actions, checkpoint, evidence):
    return {
        "title": title,
        "purpose": purpose,
        "actions": actions,
        "checkpoint": checkpoint,
        "evidence": evidence,
    }


CURRICULUM = [
    {
        "number": 1,
        "phase": "Position the experience",
        "title": "Turn a Bootcamp Project Into Real Experience",
        "focus": "Understand why the project matters and learn to describe your contribution honestly and confidently.",
        "estimated_time": "4 to 6 hours",
        "tools": ["Bootcamp project notes", "Salesforce org screenshots", "Project presentation", "Voice recorder"],
        "objectives": [
            "Separate training experience from paid employment without minimizing the work.",
            "Explain the business problem, users, scope, and your personal contribution.",
            "Build a concise project story that can expand into deeper technical answers.",
        ],
        "topics": ["Project ownership", "Business problem", "Your role", "Interview-ready project summary"],
        "deliverables": ["60-second project introduction", "Personal responsibility statement", "Project evidence inventory"],
        "interview": "Tell me about the Salesforce project you worked on.",
        "prompt": "Explain the business problem, users, your responsibilities, and the result without presenting the project as paid employment.",
        "steps": [
            step(
                "Inventory the project evidence",
                "Build a factual record before trying to sound impressive.",
                [
                    "List every requirement, object, field, automation, report, dashboard, class, integration, or presentation you personally touched.",
                    "Mark each item as designed, configured, developed, tested, documented, presented, or only observed.",
                    "Collect screenshots, diagrams, user stories, test evidence, and presentation slides that support the list.",
                    "Remove anything you cannot explain or prove.",
                ],
                "Every claimed responsibility has at least one supporting artifact or a clear explanation of how it was completed.",
                "A project evidence inventory with responsibility type and supporting proof.",
            ),
            step(
                "Define the business problem",
                "Interviewers remember business context more than a list of Salesforce features.",
                [
                    "Write the organization type and the users the application serves.",
                    "Describe the old process, its pain points, and the business risk of leaving it unchanged.",
                    "Write one measurable or observable success outcome.",
                    "Reduce the explanation to three sentences: before, need, expected result.",
                ],
                "A non-Salesforce person can understand why the project was needed.",
                "A three-sentence business problem statement.",
            ),
            step(
                "Map your contribution",
                "Use precise ownership language instead of saying that the team did everything.",
                [
                    "Create three columns: I owned, I contributed, I learned from others.",
                    "Place each project activity in exactly one column.",
                    "For every item you owned, add the decision you made and the reason.",
                    "Prepare one honest sentence explaining that the work was completed in a structured bootcamp project environment.",
                ],
                "Your explanation distinguishes your work from team work and does not imply employment experience.",
                "A personal responsibility statement and ownership map.",
            ),
            step(
                "Build the 60-second answer",
                "Create a reliable opening answer that gives the interviewer clear follow-up paths.",
                [
                    "Use this order: project context, business problem, users, your role, major solution, result, lesson.",
                    "Keep the first draft between 130 and 170 words.",
                    "Remove feature lists that do not support the story.",
                    "End with one technical area the interviewer can ask about next.",
                ],
                "The answer takes 45 to 75 seconds and includes specific ownership.",
                "A written and recorded 60-second project introduction.",
            ),
            step(
                "Prepare the deep-dive map",
                "Be ready when the interviewer asks how the solution actually worked.",
                [
                    "Create five branches: requirements, data model, security, automation, testing and delivery.",
                    "Add two facts or decisions under each branch.",
                    "Identify one mistake, challenge, or trade-off you can discuss honestly.",
                    "Practice moving from the short answer into any branch without restarting the whole story.",
                ],
                "You can answer a follow-up in each branch using a concrete project example.",
                "A one-page project deep-dive map.",
            ),
            step(
                "Record and self-review",
                "Improve clarity through evidence, not memorization alone.",
                [
                    "Record the answer twice without reading.",
                    "Check whether you said what you personally did, why decisions were made, and what changed.",
                    "Remove filler words, vague claims, and unsupported results.",
                    "Write the strongest final version and one improvement goal for next week.",
                ],
                "The final answer sounds natural, accurate, and specific rather than memorized.",
                "Final script, recording link or file, and self-review note.",
            ),
        ],
        "quality_gate": [
            "I clearly state that this was a structured project experience, not paid employment.",
            "I can prove or explain every responsibility I claim.",
            "My opening answer includes the business problem and my personal contribution.",
            "I am ready for follow-up questions on requirements, design, security, automation, and testing.",
        ],
    },
    {
        "number": 2,
        "phase": "Requirement understanding",
        "title": "Discover the Real Business Need",
        "focus": "Move beyond requested features and identify the business problem, stakeholders, constraints, and success criteria.",
        "estimated_time": "5 to 7 hours",
        "tools": ["Requirement worksheet", "Stakeholder map", "Process notes", "Interview practice partner"],
        "objectives": [
            "Ask questions that uncover the real need behind a requested feature.",
            "Separate current-state problems, desired outcomes, constraints, and assumptions.",
            "Produce a problem statement that is ready for analysis.",
        ],
        "topics": ["Stakeholder questions", "Current-state pain points", "Scope boundaries", "Acceptance criteria"],
        "deliverables": ["Discovery question set", "Problem statement", "Stakeholder and constraint map"],
        "interview": "How do you gather and clarify requirements?",
        "prompt": "Show how you would challenge an unclear request and turn it into an actionable requirement.",
        "steps": [
            step(
                "Start with the request, not the solution",
                "Avoid accepting a requested feature before understanding the problem.",
                [
                    "Choose one major feature from the bootcamp project.",
                    "Write the original request exactly as a stakeholder might say it.",
                    "Underline words that are ambiguous, subjective, or already assume a solution.",
                    "Rewrite the request as a neutral business question.",
                ],
                "The rewritten question can be answered without assuming Flow, Apex, an object, or a specific UI.",
                "Original request, ambiguity notes, and neutral business question.",
            ),
            step(
                "Identify stakeholders and decisions",
                "Requirements change depending on who uses, owns, approves, or is affected by the process.",
                [
                    "List primary users, managers, administrators, compliance or security stakeholders, and external users.",
                    "For each stakeholder, record what they do, what they need to decide, and what data they require.",
                    "Mark who can approve scope and who only provides input.",
                    "Identify stakeholders who may have conflicting goals.",
                ],
                "Every important decision has an owner and every major user group is represented.",
                "Stakeholder and decision-rights map.",
            ),
            step(
                "Document the current state",
                "A good solution must improve a real process rather than replace an imagined one.",
                [
                    "Write the current process from trigger to completion in numbered steps.",
                    "Record handoffs, spreadsheets, emails, duplicate entry, waiting time, and failure points.",
                    "Identify where data is created, changed, approved, and reported.",
                    "Add the business impact of the three most important pain points.",
                ],
                "The process includes people, data, decisions, and failure points, not only system screens.",
                "Current-state process and pain-point summary.",
            ),
            step(
                "Run structured discovery",
                "Use repeatable question categories so important areas are not missed.",
                [
                    "Create questions under: goals, users, process, data, security, volume, exceptions, reporting, integrations, and success.",
                    "Write at least two open questions in each category.",
                    "Add one challenge question that tests whether the requested feature is necessary.",
                    "Role-play the discovery conversation and record incomplete answers or new assumptions.",
                ],
                "The question set could support a 30-minute stakeholder discovery meeting.",
                "A categorized discovery question set with at least 20 questions.",
            ),
            step(
                "Define scope and constraints",
                "Prevent the requirement from growing without control.",
                [
                    "Write what is in scope, out of scope, and deferred.",
                    "Document timeline, budget, licensing, security, data quality, integration, and user-adoption constraints.",
                    "List assumptions that require validation.",
                    "Identify the smallest useful outcome that could be delivered first.",
                ],
                "A reviewer can tell what will not be delivered and why.",
                "Scope boundary, constraint list, assumptions, and minimum useful outcome.",
            ),
            step(
                "Write the final problem statement",
                "Create a shared definition of the need before solution design begins.",
                [
                    "Use this format: For [users], the current [process] causes [problems], resulting in [impact].",
                    "Add the desired outcome and how success will be observed.",
                    "Check the statement against stakeholder notes and constraints.",
                    "Prepare a two-minute interview answer explaining your discovery method using this example.",
                ],
                "The statement describes the need without prescribing the technical implementation.",
                "Final problem statement and two-minute requirement-gathering answer.",
            ),
        ],
        "quality_gate": [
            "I can explain why the original request was incomplete or solution-biased.",
            "I identified users, decision-makers, constraints, exceptions, and success criteria.",
            "My problem statement does not prescribe a Salesforce feature.",
            "I can describe my discovery method using a specific project example.",
        ],
    },
    {
        "number": 3,
        "phase": "Requirement analysis",
        "title": "Convert Requirements Into Salesforce Language",
        "focus": "Translate business language into user stories, process steps, data needs, security needs, and testable outcomes.",
        "estimated_time": "5 to 7 hours",
        "tools": ["User-story template", "Process diagram tool", "Data model sketch", "Acceptance-criteria checklist"],
        "objectives": [
            "Turn discovery results into testable user stories and acceptance criteria.",
            "Identify data, access, automation, reporting, and integration implications.",
            "Recognize gaps before configuration or development begins.",
        ],
        "topics": ["User stories", "Process mapping", "Data relationships", "Security questions", "Definition of done"],
        "deliverables": ["Three user stories", "High-level process map", "Acceptance criteria and edge cases"],
        "interview": "How do you make sure a requirement is ready for development?",
        "prompt": "Explain what must be known before configuration or development starts.",
        "steps": [
            step(
                "Break the need into user outcomes",
                "Avoid creating one oversized requirement that hides different users and decisions.",
                [
                    "Review the Week 2 problem statement and stakeholder map.",
                    "List each distinct user outcome required to solve the problem.",
                    "Separate create, review, approve, notify, report, and exception-handling outcomes.",
                    "Group outcomes into must-have, should-have, and later.",
                ],
                "Each outcome belongs to a clear user and can be evaluated independently.",
                "Prioritized user-outcome list.",
            ),
            step(
                "Write testable user stories",
                "Make the user, capability, and value explicit.",
                [
                    "Write at least three stories using: As a [user], I want [capability], so that [value].",
                    "Avoid technical implementation words unless the user genuinely needs that technology.",
                    "Add a business rule or constraint to each story.",
                    "Check that every story supports the Week 2 problem statement.",
                ],
                "Each story has one user, one primary outcome, and one business value.",
                "Three refined user stories.",
            ),
            step(
                "Map the future process",
                "Show how people, data, decisions, and systems interact after the change.",
                [
                    "Draw the trigger, main path, decisions, approvals, exceptions, and completion state.",
                    "Mark manual and automated steps separately.",
                    "Identify where users need visibility, notifications, or reports.",
                    "Compare the future process to the current-state pain points.",
                ],
                "Every major pain point is removed, reduced, or intentionally accepted.",
                "High-level future-state process map.",
            ),
            step(
                "Identify Salesforce data and security needs",
                "Prepare the requirement for platform design without prematurely building it.",
                [
                    "List records that must exist, the information each record holds, and key relationships.",
                    "Identify record ownership and who must create, read, edit, approve, or report on the data.",
                    "Mark sensitive fields and external-user access needs.",
                    "Record data volume, duplicate, retention, and migration questions.",
                ],
                "The data and access questions are detailed enough for a solution designer to evaluate standard and custom options.",
                "Data and access requirement table.",
            ),
            step(
                "Write acceptance criteria and edge cases",
                "Define observable outcomes so the requirement can be tested.",
                [
                    "Write Given, When, Then criteria for the normal path.",
                    "Add criteria for missing data, duplicate data, unauthorized users, failed approvals, and integration failure.",
                    "Include reporting or notification outcomes where relevant.",
                    "Confirm each criterion can be tested without interpreting vague words such as fast, easy, or user-friendly.",
                ],
                "A tester could determine pass or fail from each criterion.",
                "Acceptance criteria and edge-case matrix.",
            ),
            step(
                "Run the ready-for-development check",
                "Find unanswered questions before work is estimated or assigned.",
                [
                    "Check clarity, business value, dependencies, data, security, exceptions, acceptance criteria, and decision ownership.",
                    "List unresolved questions and assign an owner to each.",
                    "State whether the requirement is ready, conditionally ready, or not ready.",
                    "Prepare an interview answer using one gap you found and how you resolved it.",
                ],
                "The readiness decision is supported by specific evidence, not intuition.",
                "Readiness checklist, open-question log, and interview answer.",
            ),
        ],
        "quality_gate": [
            "My user stories describe outcomes and value rather than only technical tasks.",
            "My future-state process includes decisions, exceptions, and ownership.",
            "I identified data, security, reporting, integration, and volume questions.",
            "Every acceptance criterion has an observable pass or fail result.",
        ],
    },
    {
        "number": 4,
        "phase": "Research skills",
        "title": "Research Before You Recommend",
        "focus": "Use official documentation, release notes, trusted community sources, and comparisons to support a technical decision.",
        "estimated_time": "6 to 8 hours",
        "tools": ["Salesforce Help", "Salesforce Developer documentation", "Trailhead", "Comparison matrix", "Presentation software"],
        "objectives": [
            "Turn an unfamiliar Salesforce topic into focused research questions.",
            "Evaluate authority, recency, evidence, limitations, and project relevance.",
            "Compare options and make a recommendation that can be defended in an interview.",
        ],
        "topics": ["Research questions", "Source quality", "Option comparison", "Evidence-based recommendation"],
        "deliverables": ["Research brief", "Source list", "Options and trade-offs", "Five-minute research presentation"],
        "interview": "How do you approach a Salesforce feature you have never used before?",
        "prompt": "Describe your research method, how you validate sources, and how you decide when you know enough.",
        "steps": [
            step(
                "Choose a decision, not only a topic",
                "Research should answer a practical question rather than collect random facts.",
                [
                    "Select an unfamiliar Salesforce feature, pattern, integration method, or architectural choice related to the project.",
                    "Write one primary decision question and three supporting questions.",
                    "Define the project context, users, constraints, and expected scale.",
                    "State what a useful final recommendation must decide.",
                ],
                "The research question can lead to a specific recommendation for the project.",
                "Primary question, subquestions, and decision context.",
            ),
            step(
                "Read official sources first",
                "Establish the platform facts before reading opinions.",
                [
                    "Find at least one Salesforce Help or Developer documentation source.",
                    "Find one Trailhead, architect, release-note, or official engineering source.",
                    "Record title, publisher, update date if available, relevant section, and a two-sentence summary.",
                    "Capture limitations, prerequisites, licensing, security, or governor-limit considerations.",
                ],
                "At least two official sources directly answer part of the research question.",
                "Official-source notes with citations and limitations.",
            ),
            step(
                "Add practical evidence",
                "Understand how the feature behaves outside a summary page.",
                [
                    "Find one credible implementation article, sample repository, conference session, or technical walkthrough.",
                    "Record the scenario, assumptions, implementation pattern, evidence, and known limitations.",
                    "Reject sources that only repeat marketing claims or do not show technical detail.",
                    "Compare the practical source with official documentation and note any disagreement.",
                ],
                "The practical source adds implementation detail or a limitation not obvious from the official sources.",
                "Practical-source analysis and comparison notes.",
            ),
            step(
                "Create a claim-evidence table",
                "Separate what is known from what is assumed.",
                [
                    "Create columns: claim, evidence, source, project impact, confidence.",
                    "Add at least six claims that matter to the decision.",
                    "Paraphrase sources accurately and attach a citation to each claim.",
                    "Mark any claim that still requires testing or stakeholder confirmation.",
                ],
                "Every recommendation-relevant claim has evidence and a project connection.",
                "Six-row claim-evidence-project table.",
            ),
            step(
                "Compare alternatives",
                "Show engineering judgment rather than declaring one feature universally best.",
                [
                    "Compare at least two viable approaches.",
                    "Score security, maintainability, scale, user experience, testing, deployment, cost or licensing, and project fit.",
                    "Explain trade-offs and the conditions under which each option becomes preferable.",
                    "Select the recommendation and identify one validation step before final approval.",
                ],
                "The recommendation follows from the criteria and acknowledges a credible alternative.",
                "Comparison matrix and justified recommendation.",
            ),
            step(
                "Build the five-minute presentation",
                "Communicate research as a decision, not a textbook summary.",
                [
                    "Use six sections: question, context, key facts, options, recommendation, limitation or next step.",
                    "Use one diagram or comparison table and cite sources on the relevant slide.",
                    "Keep definitions short and spend most time on project impact and trade-offs.",
                    "Practice answering: Why this source? Why this option? What would change your decision?",
                ],
                "The presentation explains a project decision in five minutes and supports claims with credible evidence.",
                "Research brief, source list, comparison matrix, and presentation file or link.",
            ),
        ],
        "quality_gate": [
            "I used at least two official Salesforce sources and one credible practical source.",
            "Every important claim has evidence and a project connection.",
            "I compared at least two viable options using explicit criteria.",
            "My recommendation includes trade-offs, limitations, and a validation step.",
        ],
    },
    {
        "number": 5,
        "phase": "Building theory",
        "title": "Design the Solution Before Building",
        "focus": "Create a defensible Salesforce solution design without performing practical implementation yet.",
        "estimated_time": "6 to 8 hours",
        "tools": ["Architecture one-pager", "Data model sketch", "Security matrix", "Automation decision table"],
        "objectives": [
            "Translate analyzed requirements into a coherent Salesforce solution design.",
            "Choose standard or custom capabilities using explicit criteria.",
            "Explain data, security, automation, integration, and user-experience decisions before building.",
        ],
        "topics": ["Standard versus custom", "Data model", "Security model", "Automation selection", "Integration boundaries"],
        "deliverables": ["Solution architecture one-pager", "Object relationship sketch", "Automation decision table"],
        "interview": "Why did you choose Flow, Apex, or another Salesforce capability?",
        "prompt": "Defend your design using maintainability, security, scale, and user experience.",
        "steps": [
            step(
                "Set the design principles",
                "Make the decision criteria visible before selecting features.",
                [
                    "Review the Week 2 and Week 3 requirements, constraints, and acceptance criteria.",
                    "Choose five design principles such as security, maintainability, user simplicity, scalability, auditability, or reuse.",
                    "Rank the principles for this project and explain the ranking.",
                    "List non-negotiable constraints that the design must respect.",
                ],
                "Future design decisions can be evaluated against stated principles rather than preference.",
                "Ranked design principles and non-negotiable constraints.",
            ),
            step(
                "Evaluate standard before custom",
                "Use platform capabilities intentionally and avoid unnecessary complexity.",
                [
                    "For each major requirement, list relevant standard objects, standard features, Flow, approval, reports, Experience Cloud, Apex, LWC, or integration options.",
                    "Record fit, gaps, licensing, limits, maintainability, and user impact.",
                    "Identify where configuration is sufficient and where custom development may be justified.",
                    "State what evidence would be required before approving custom code.",
                ],
                "Every custom element solves a documented gap that cannot be handled acceptably by a simpler option.",
                "Standard-versus-custom decision table.",
            ),
            step(
                "Design the conceptual data model",
                "Create the record structure without configuring the org yet.",
                [
                    "List the business entities and decide whether each maps to a standard object, custom object, field, or external data source.",
                    "Draw key relationships and state why lookup, master-detail, junction, or indirect relationships are appropriate.",
                    "Identify ownership, required fields, duplicate strategy, lifecycle status, and reporting needs.",
                    "Note data volume, migration, retention, and integration implications.",
                ],
                "The model supports the process, security, reporting, and expected volume without unnecessary objects.",
                "Conceptual object relationship diagram and data decision notes.",
            ),
            step(
                "Design security from the user outward",
                "Avoid treating security as a final configuration task.",
                [
                    "List user groups and the records and fields each group needs to create, read, edit, delete, approve, or report on.",
                    "Define the likely OWD baseline, role or territory need, sharing mechanisms, permission sets, and sensitive-field controls.",
                    "Identify external-user and integration-user access separately.",
                    "Describe how the design follows least privilege and how access will be tested.",
                ],
                "Every access requirement has a mechanism and no user receives access only for convenience.",
                "Security access matrix and proposed sharing model.",
            ),
            step(
                "Choose automation and integration boundaries",
                "Select the right execution model before implementation.",
                [
                    "List each event, decision, action, error path, and volume expectation.",
                    "Compare record-triggered Flow, screen Flow, approval, scheduled Flow, Apex, platform events, APIs, and external processing where relevant.",
                    "Identify transaction boundaries, retries, idempotency, limits, and error logging needs.",
                    "Choose the proposed option and explain why the alternatives were not selected.",
                ],
                "Each automation and integration choice is justified by complexity, volume, security, reliability, and maintainability.",
                "Automation and integration decision table.",
            ),
            step(
                "Assemble the architecture one-pager",
                "Present the design as one connected solution rather than isolated features.",
                [
                    "Show users and channels, Salesforce data, automation, security, integration boundaries, and reporting.",
                    "Add five numbered decisions with short reasons.",
                    "Include assumptions, risks, and open questions.",
                    "Practice a five-minute design explanation without claiming the solution has already been built.",
                ],
                "The one-pager can be understood by both a business stakeholder and a Salesforce interviewer.",
                "Solution architecture one-pager and five-minute explanation notes.",
            ),
        ],
        "quality_gate": [
            "This week is design theory only; I do not claim configuration or code that was not completed.",
            "Every custom component solves a documented requirement or platform gap.",
            "The data, security, automation, integration, and reporting decisions support one coherent process.",
            "I can explain the trade-offs behind each major platform choice.",
        ],
    },
    {
        "number": 6,
        "phase": "Building theory",
        "title": "Plan Quality, Testing, and Delivery",
        "focus": "Explain how a professional team would build, test, deploy, document, and support the proposed solution.",
        "estimated_time": "6 to 8 hours",
        "tools": ["Implementation backlog", "Test matrix", "Deployment checklist", "Risk register"],
        "objectives": [
            "Turn the design into a safe implementation sequence without performing the build.",
            "Plan positive, negative, security, volume, integration, and user-acceptance testing.",
            "Explain deployment, rollback, monitoring, documentation, and support responsibilities.",
        ],
        "topics": ["Build sequence", "Test scenarios", "Data quality", "Deployment planning", "Risk management"],
        "deliverables": ["Implementation plan", "Test scenario matrix", "Risk and mitigation register"],
        "interview": "How would you safely deliver this solution to production?",
        "prompt": "Walk through development order, testing, deployment, rollback, and post-release checks.",
        "steps": [
            step(
                "Break the design into deliverable work",
                "Create an implementation sequence that respects dependencies.",
                [
                    "Convert the Week 5 design into work items for data, security, automation, integration, UI, reporting, testing, documentation, and training.",
                    "Identify dependencies and the minimum vertical slice that proves the core process.",
                    "Mark work that can run in parallel and work that must be sequential.",
                    "Define the expected output and owner role for each work item.",
                ],
                "The sequence avoids building automation or UI before the required data and access foundations exist.",
                "Prioritized implementation backlog with dependencies and owners.",
            ),
            step(
                "Define development and review standards",
                "Explain how quality is built into the work rather than checked only at the end.",
                [
                    "Define naming, descriptions, help text, source control, branching, code review, and documentation expectations.",
                    "State when Flow, Apex, LWC, validation, duplicate rules, or metadata review require specialized testing.",
                    "Add security review requirements for CRUD, FLS, sharing, secrets, and integration access.",
                    "Define what must be demonstrated before a work item is considered complete.",
                ],
                "The definition of done includes functional, security, testing, documentation, and review evidence.",
                "Development standards and definition-of-done checklist.",
            ),
            step(
                "Build the test matrix",
                "Cover the ways real users and data can make the solution fail.",
                [
                    "Create scenarios for normal, boundary, negative, duplicate, unauthorized, high-volume, integration-failure, and retry behavior.",
                    "Map each test to a requirement or acceptance criterion.",
                    "Record test data, expected result, owner, and evidence.",
                    "Include regression tests for existing processes that could be affected.",
                ],
                "Every acceptance criterion and major risk has at least one test scenario.",
                "Complete test scenario matrix.",
            ),
            step(
                "Plan data and deployment",
                "Prevent release failures caused by order, access, or data readiness.",
                [
                    "Document source-control promotion, environment sequence, validation, approvals, and deployment order.",
                    "Identify data cleanup, migration, mapping, reconciliation, and backup needs.",
                    "Define pre-deployment, deployment, and post-deployment tasks with owners.",
                    "State the rollback or forward-fix approach for metadata, code, integration, and data issues.",
                ],
                "The plan identifies how to recover if the release or migrated data is incorrect.",
                "Deployment runbook and data-readiness checklist.",
            ),
            step(
                "Plan adoption, monitoring, and support",
                "A release is not complete when metadata reaches production.",
                [
                    "Identify training audiences, job aids, release communication, and user-support channels.",
                    "Define operational metrics, error logs, dashboards, alerts, and adoption indicators.",
                    "Assign ownership for production issues, enhancement requests, and documentation updates.",
                    "Schedule post-release validation and a retrospective.",
                ],
                "The plan explains how the team will know whether the solution works and whether users adopt it.",
                "Adoption, monitoring, and support plan.",
            ),
            step(
                "Create the risk register and interview answer",
                "Show that delivery planning includes uncertainty and mitigation.",
                [
                    "List at least eight risks across requirements, data, security, limits, integration, deployment, adoption, and schedule.",
                    "Score likelihood and impact, then assign prevention, contingency, and owner.",
                    "Select the three most serious risks and explain the mitigation sequence.",
                    "Practice a three-minute production-delivery answer using the implementation and test plans.",
                ],
                "The answer covers build order, testing, deployment, rollback, monitoring, and ownership.",
                "Risk register and final delivery interview answer.",
            ),
        ],
        "quality_gate": [
            "This week is delivery planning only; I do not claim that the planned implementation was completed.",
            "Every work item has an output, dependency, owner role, and definition of done.",
            "The test matrix includes negative, security, volume, and failure scenarios.",
            "The deployment plan includes data readiness, rollback, monitoring, adoption, and support.",
        ],
    },
    {
        "number": 7,
        "phase": "Presentation skills",
        "title": "Present the Project as a Consultant",
        "focus": "Build a clear story that starts with business value and uses technical detail only where it supports the decision.",
        "estimated_time": "6 to 9 hours",
        "tools": ["Project sample deck", "Presentation software", "Screen recorder", "Timer", "Q&A worksheet"],
        "objectives": [
            "Structure a project presentation around problem, decisions, solution, value, and lessons.",
            "Use architecture and process visuals instead of text-heavy technical lists.",
            "Present clearly in seven minutes and handle follow-up questions professionally.",
        ],
        "topics": ["Executive opening", "Problem-solution-result story", "Architecture visuals", "Demo narration", "Q&A control"],
        "deliverables": ["Eight-slide project deck", "Seven-minute presentation", "Question-and-answer preparation"],
        "interview": "Present a Salesforce solution you designed.",
        "prompt": "Lead with the problem and value, then explain the design, decisions, risks, and result.",
        "steps": [
            step(
                "Define the audience and message",
                "A presentation changes depending on whether the audience is a recruiter, manager, architect, or business stakeholder.",
                [
                    "Choose the primary audience for the presentation.",
                    "Write the one sentence you want the audience to remember.",
                    "List the three questions that audience is most likely to care about.",
                    "Remove details that do not support those questions or the central message.",
                ],
                "Every planned slide supports the audience, central message, or an expected question.",
                "Audience statement, central message, and audience-question list.",
            ),
            step(
                "Build the eight-slide story",
                "Control the narrative before designing slides.",
                [
                    "Use this sequence: title and outcome, business problem, users and requirements, process and data model, security and automation decisions, delivery and quality plan, value and lessons, close and questions.",
                    "Write one sentence for the purpose of each slide.",
                    "Assign a maximum speaking time to each slide totaling seven minutes.",
                    "Check that the story clearly identifies your personal contribution.",
                ],
                "The slide sequence forms one story and does not repeat the same feature list.",
                "Eight-slide outline and timing plan.",
            ),
            step(
                "Design evidence-led slides",
                "Use visuals to make decisions understandable.",
                [
                    "Use diagrams, process flows, object relationships, decision tables, screenshots, or simple metrics where they add evidence.",
                    "Limit each slide to one main idea and remove paragraphs that belong in speaker notes.",
                    "Use consistent labels and explain every acronym the first time it appears.",
                    "Cite research sources and label planned features honestly when they were not built.",
                ],
                "A viewer can understand the main point of each slide within five seconds.",
                "Completed eight-slide presentation deck.",
            ),
            step(
                "Write the spoken narrative",
                "Slides support the explanation; they do not replace it.",
                [
                    "Write the opening, transitions, decision explanations, and closing in conversational language.",
                    "For every technical decision, state the requirement, options, choice, and trade-off.",
                    "Use precise ownership language and distinguish completed project work from later design recommendations.",
                    "End with what you learned and what you would improve.",
                ],
                "The narrative can be understood without reading the slide text aloud.",
                "Speaker notes or presentation script.",
            ),
            step(
                "Practice the seven-minute delivery",
                "Improve timing, confidence, and clarity through repeated review.",
                [
                    "Record three full attempts with a timer.",
                    "Review pace, filler words, eye contact, slide dependence, transitions, and technical clarity.",
                    "Cut content rather than speaking faster when the presentation exceeds seven minutes.",
                    "Repeat the final version without reading full sentences.",
                ],
                "The final presentation is between six and eight minutes and sounds natural.",
                "Final recording and self-review scorecard.",
            ),
            step(
                "Prepare and control Q&A",
                "Interview value often appears in the discussion after the formal presentation.",
                [
                    "Write at least 15 likely questions across requirements, security, data, automation, testing, trade-offs, mistakes, and personal contribution.",
                    "Prepare concise answers using decision, reason, evidence, and limitation.",
                    "Practice clarifying unclear questions before answering.",
                    "Prepare an honest response for questions about work you did not personally complete.",
                ],
                "You can answer expected questions directly and acknowledge uncertainty without guessing.",
                "Q&A bank with 15 questions and answers.",
            ),
            step(
                "Use the sample as a quality reference",
                "Study structure and communication without copying content blindly.",
                [
                    "Review the improved project presentation sample in the portal.",
                    "Identify three structural choices, three visual choices, and two areas you would adapt differently for your project.",
                    "Compare your deck against the sample for business context, architecture, decisions, value, and close.",
                    "Document the improvements you made after the comparison.",
                ],
                "Your deck follows professional principles while remaining specific to your own project and contribution.",
                "Sample comparison and final revision note.",
            ),
        ],
        "quality_gate": [
            "The presentation begins with a business problem and ends with value and lessons.",
            "Every technical slide explains a decision or supports evidence.",
            "The delivery fits within seven minutes without rushing.",
            "I prepared direct answers for ownership, trade-offs, testing, security, and improvement questions.",
        ],
    },
    {
        "number": 8,
        "phase": "Interview readiness",
        "title": "Defend Your Decisions in a Salesforce Interview",
        "focus": "Connect the full project story to behavioral, admin, developer, and solution-design interview questions.",
        "estimated_time": "7 to 10 hours",
        "tools": ["Question bank", "STAR worksheet", "Video meeting or recorder", "Mock interview scorecard", "30-day plan"],
        "objectives": [
            "Answer project, behavioral, admin, developer, and design questions with specific evidence.",
            "Defend decisions and trade-offs without overstating experience.",
            "Use mock interview feedback to create a focused improvement plan.",
        ],
        "topics": ["STAR answers", "Technical defense", "Honest experience positioning", "Mock interview", "Improvement plan"],
        "deliverables": ["Final project story", "Ten interview answers", "Mock interview scorecard", "30-day improvement plan"],
        "interview": "What did you personally do, what was difficult, and what would you improve?",
        "prompt": "Answer with specific decisions, evidence, lessons, and clear ownership of your contribution.",
        "steps": [
            step(
                "Build the interview question map",
                "Prepare by category so answers connect rather than exist as isolated scripts.",
                [
                    "Create categories for project overview, requirements, data, security, automation, development, testing, deployment, teamwork, challenge, failure, and improvement.",
                    "Write at least five questions in each category.",
                    "Mark the ten questions most likely for the target role.",
                    "Map each priority question to a specific project example or design decision.",
                ],
                "Every priority question has a real example, decision, or clearly stated learning gap.",
                "Categorized question bank and top-ten priority list.",
            ),
            step(
                "Prepare behavioral answers with STAR plus learning",
                "Use structure while showing reflection and growth.",
                [
                    "Choose examples for ambiguity, disagreement, mistake, deadline, learning a new feature, quality issue, and receiving feedback.",
                    "Write Situation and Task briefly, then emphasize your Action, reasoning, Result, and Learning.",
                    "Separate team outcomes from your own actions.",
                    "Remove invented metrics and replace them with observable outcomes when exact numbers are unavailable.",
                ],
                "Each answer identifies what you personally did and what changed because of the action.",
                "At least seven STAR-plus-learning answers.",
            ),
            step(
                "Prepare technical defense answers",
                "Show judgment, not only feature definitions.",
                [
                    "For each major project decision, write the requirement, considered options, chosen approach, reason, trade-off, test plan, and improvement.",
                    "Prepare answers for standard versus custom, Flow versus Apex, relationship choice, sharing model, bulk behavior, error handling, and deployment.",
                    "State which items were actually implemented and which were theoretical design work.",
                    "Practice explaining one decision at business, admin, developer, and architect depth.",
                ],
                "You can explain the same decision at different technical depths without contradicting yourself.",
                "Technical decision defense sheet.",
            ),
            step(
                "Practice honest experience positioning",
                "Confidence and accuracy are stronger than inflated titles or invented employment.",
                [
                    "Write a direct answer to: How much professional Salesforce experience do you have?",
                    "Explain the bootcamp structure, project scope, your contribution, review process, and artifacts.",
                    "Prepare a transition from limited employment experience to demonstrated capability and learning speed.",
                    "Practice saying I have not done that in production, followed by how you would research, design, test, and validate it.",
                ],
                "The answer is honest, confident, and immediately supported by project evidence.",
                "Experience-positioning answer and uncertainty-response template.",
            ),
            step(
                "Run the mock interview",
                "Test recall, reasoning, communication, and composure under realistic pressure.",
                [
                    "Complete a 30- to 45-minute mock interview with project, behavioral, and technical questions.",
                    "Do not read prepared scripts during the interview.",
                    "Have the interviewer score clarity, specificity, correctness, ownership, reasoning, and confidence.",
                    "Record questions that caused confusion, long answers, guessing, or missing evidence.",
                ],
                "The mock interview produces specific evidence about strengths and gaps.",
                "Recording or interviewer notes and completed mock interview scorecard.",
            ),
            step(
                "Revise the final answer set",
                "Use mock evidence to improve weak reasoning and communication.",
                [
                    "Rewrite the ten priority answers using the feedback.",
                    "Add missing examples, technical facts, trade-offs, or clearer ownership.",
                    "Shorten answers that exceed two minutes unless a deep dive is requested.",
                    "Run a second mini-interview focused only on the weakest areas.",
                ],
                "The revised answers are direct, specific, technically defensible, and appropriately timed.",
                "Final ten-answer interview set and second-practice notes.",
            ),
            step(
                "Create the 30-day improvement plan",
                "Convert remaining gaps into a realistic next learning cycle.",
                [
                    "Rank gaps by interview impact and role relevance.",
                    "Choose no more than three technical goals and two communication goals.",
                    "Define weekly practice, evidence, and completion criteria for each goal.",
                    "Schedule another mock interview and portfolio review at the end of the plan.",
                ],
                "Every goal has a deadline, practice method, and observable evidence of improvement.",
                "Thirty-day improvement plan and final readiness reflection.",
            ),
        ],
        "quality_gate": [
            "I can explain my project, decisions, personal contribution, challenges, and improvements without overstating experience.",
            "My priority answers use specific evidence and remain under two minutes unless a deep dive is requested.",
            "I can defend standard/custom, data, security, automation, testing, and delivery decisions.",
            "My 30-day plan targets the most important remaining technical and communication gaps.",
        ],
    },
]
