"""Default Salesforce project and certification content."""

CERTIFICATIONS = [
    {"code": "ADMIN", "name": "Salesforce Certified Administrator", "short_name": "Administrator", "sort_order": 1},
    {"code": "PDI", "name": "Salesforce Certified Platform Developer I", "short_name": "Platform Developer I", "sort_order": 2},
]

HR_PROJECT = {
    "name": "HR Management Application",
    "slug": "hr-management-application",
    "short_name": "HR Management App",
    "summary": "A Salesforce solution for positions, candidates, interviewers, HR managers, recruitment activity, service requests, reporting, integrations, and external experiences.",
    "business_problem": "Recruiters need one secure system to manage hiring operations, communication, scheduling, candidate participation, reporting, and external access.",
    "users": "HR Managers\nCandidates\nInterviewers\nSalesforce Administrators\nPublic and authenticated Experience Cloud users",
    "objects": "Location\nHR Manager\nPosition\nCandidate\nInterviewer\nPosition Candidate\nPosition Interviewer\nError Log\nLead\nCase\nEmail Message",
    "outcomes": "Recruitment Management Lightning application\nControlled data and security model\nDeclarative and Apex automation\nAddress verification and REST integrations\nReusable Lightning Web Components\nExperience Cloud site\nEmail-to-Case workflow",
    "source_filename": "HR_Management_Application_Source.md",
}


def project_step(number, phase, title, summary, tasks, deliverables, definition_of_done, review_questions, source_reference):
    return {
        "step_number": number,
        "phase": phase,
        "title": title,
        "summary": summary,
        "tasks": tasks,
        "deliverables": deliverables,
        "definition_of_done": definition_of_done,
        "review_questions": review_questions,
        "source_reference": source_reference,
    }


HR_PROJECT_STEPS = [
    project_step(1, "Foundation", "Object, application, validation, duplicate, and security setup",
        "Build the core data model and secure the application before automation begins.",
        ["Create the Recruitment Management Lightning application.", "Create core and junction objects with fields, descriptions, and help text.", "Create validation and duplicate rules.", "Configure permission sets, roles, organization-wide defaults, and sharing.", "Create test users and verify access."],
        ["ERD", "Object and field inventory", "Validation and duplicate-rule evidence", "Security matrix", "Access test screenshots"],
        ["All required objects and relationships exist.", "Security is least-privilege and tested with multiple users.", "Data-quality rules have positive and negative tests."],
        ["Why did you choose each relationship type?", "How do object, field, and record access differ?", "What data-quality problem does each rule prevent?"],
        "Source project foundation and security requirements."),
    project_step(2, "Foundation", "Reports and dashboard",
        "Create operational visibility for positions and candidates.",
        ["Create a Position-Candidate report with candidate counts.", "Create a Position report grouped by year.", "Add charts to a management dashboard.", "Validate filters, labels, access, and business meaning."],
        ["Two reports", "One dashboard", "Screenshots", "Business-value explanation"],
        ["Reports answer defined business questions.", "Dashboard is readable and accessible to the correct users.", "Filters and groupings have been tested."],
        ["What decision can a manager make from each chart?", "How is report access controlled?", "How would high data volume affect the design?"],
        "Source project reporting requirements."),
    project_step(3, "Apex", "Position-Interviewer trigger and unit tests",
        "Prevent conflicting interviewer assignments with a bulk-safe trigger design.",
        ["Create before-insert and before-update trigger behavior.", "Move logic to a handler/service.", "Prevent duplicate or conflicting assignments.", "Create positive, negative, update, and bulk tests.", "Use meaningful assertions and security-aware data access."],
        ["Trigger", "Handler or service", "Test class", "Test results", "Design diagram"],
        ["No SOQL or DML appears in loops.", "Behavior is correct for bulk insert and update.", "Tests prove normal and failure paths."],
        ["How does the solution behave with 200 records?", "How do you prevent recursion?", "Why is this Apex rather than Flow?"],
        "Source project Apex trigger requirements."),
    project_step(4, "Apex", "Reusable Error Log service",
        "Centralize diagnostic logging for Apex processes.",
        ["Create a reusable logging service.", "Capture process, context, message, and optional stack information.", "Avoid hiding the original failure.", "Create tests and example usage."],
        ["Logging service", "Tests", "Example usage", "Operational notes"],
        ["The service can be reused by multiple processes.", "Logging failure does not create uncontrolled recursion.", "Sensitive data is not unnecessarily stored."],
        ["When should an exception be rethrown?", "What information is useful to support teams?", "How do you avoid logging sensitive data?"],
        "Source project error logging requirement."),
    project_step(5, "Apex", "Scheduled batch cleanup and completion email",
        "Automate retention cleanup and notify operational users.",
        ["Create a selective batch query.", "Process eligible records safely.", "Send a completion summary.", "Create a schedulable class.", "Document retention and recovery controls."],
        ["Batch class", "Service or handler", "Schedulable class", "Email evidence", "Safety notes"],
        ["Only eligible records are processed.", "The job is safe to rerun.", "Operational users receive a useful completion summary."],
        ["Why is Batch Apex appropriate?", "What happens if part of the batch fails?", "How would you recover incorrectly removed records?"],
        "Source project batch and scheduling requirements."),
    project_step(6, "Apex", "Batch Apex test",
        "Test asynchronous cleanup at realistic volume.",
        ["Create at least 199 relevant records.", "Execute the batch inside startTest/stopTest.", "Assert eligible and ineligible outcomes.", "Verify scheduling behavior where practical."],
        ["Batch test class", "Assertions", "Test-run evidence", "Coverage result"],
        ["Tests prove selection boundaries.", "Assertions verify data outcomes, not only coverage.", "The test is isolated and deterministic."],
        ["Why 199 records?", "What boundary cases should be added?", "How do startTest and stopTest affect asynchronous code?"],
        "Source project batch test requirement."),
    project_step(7, "Automation", "Web-to-Lead, approval, and lead conversion automation",
        "Capture public interest and route candidate and interviewer requests correctly.",
        ["Create Lead Type and approval fields.", "Generate a Web-to-Lead form.", "Create approval emails and approval process.", "Use supported record-triggered Flow rather than legacy Process Builder.", "Test duplicate, invalid, approved, and rejected paths."],
        ["Web form", "Approval process", "Flows", "Email templates", "End-to-end tests"],
        ["Each lead type follows the correct path.", "Approval decisions create the intended records and notifications.", "Failures are visible and recoverable."],
        ["Why use Flow here?", "How are duplicate submissions handled?", "What prevents unauthorized approval?"],
        "Source project lead and approval requirements, modernized to Flow."),
    project_step(8, "Automation", "Position-Candidate confirmation email Flow",
        "Confirm candidate registration with position and location information.",
        ["Create a record-triggered Flow.", "Build a clear email with related data.", "Include a map link.", "Design for bulk creation and missing data."],
        ["Flow", "Email or text template", "Bulk test evidence", "Error-path notes"],
        ["The email contains correct related data.", "The Flow handles bulk creation.", "Missing optional data does not create an unhandled failure."],
        ["How does the Flow obtain related data?", "What makes it bulk-safe?", "How would you prevent duplicate emails?"],
        "Source project confirmation email requirement."),
    project_step(9, "Integration", "Address verification",
        "Verify location addresses through an external API and store a controlled result.",
        ["Configure secure authentication.", "Create reusable callout logic.", "Expose an invocable method for Flow.", "Map valid and invalid responses.", "Create HTTP mock tests."],
        ["Named Credential or External Credential", "Callout service", "Invocable method", "Flow", "Mock tests"],
        ["No credential is hard-coded.", "Success, invalid, timeout, and error responses are tested.", "Users receive actionable errors."],
        ["How are credentials protected?", "How do retries avoid duplicate processing?", "What is logged when the provider is unavailable?"],
        "Source project address verification integration."),
    project_step(10, "Integration", "Position Apex REST service",
        "Expose eligible live positions through a stable JSON contract.",
        ["Create an Apex REST resource.", "Filter eligible positions.", "Return a stable response structure.", "Apply sharing and field access.", "Test success, empty, invalid, and permission scenarios."],
        ["REST class", "Request/response examples", "Unit tests", "Security notes"],
        ["The API contract is documented.", "Security and error status codes are appropriate.", "Tests validate serialization and filters."],
        ["How is API access authorized?", "How do you version the contract?", "What happens when no records match?"],
        "Source project REST requirement."),
    project_step(11, "Lightning Web Components", "Custom lookup and Position creation component",
        "Create reusable lookup behavior and a clean Position-entry experience.",
        ["Create a reusable custom lookup.", "Create a Position form with UI Record API where appropriate.", "Navigate to the new record.", "Handle validation and errors.", "Test keyboard and responsive behavior."],
        ["Lookup LWC", "Position form LWC", "Navigation evidence", "Error and accessibility tests"],
        ["Component responsibilities are clear.", "Errors are understandable.", "The main journey works without Apex where platform APIs are sufficient."],
        ["Why use UI Record API?", "How does the lookup communicate selection?", "How is accessibility tested?"],
        "Source project custom lookup and Position form requirements."),
    project_step(12, "Lightning Web Components", "Position Detail workspace",
        "Present Position, Interviewer, Location, and Candidate information in one workspace.",
        ["Create focused tabs or sections.", "Use LDS for primary record data.", "Query related data safely.", "Add creation actions with default values.", "Handle loading, empty, and error states."],
        ["Detail LWC", "Related-data service", "Navigation actions", "State screenshots"],
        ["Each section has one clear purpose.", "Related data respects sharing and field access.", "Loading, empty, error, and success states are complete."],
        ["Which data uses LDS and which uses Apex?", "How are related records secured?", "How would the UI perform with many related records?"],
        "Source project Position detail requirements."),
    project_step(13, "Lightning Web Components", "Live Position list and search",
        "Show eligible positions in a searchable data table.",
        ["Display current and future positions.", "Navigate from names to records.", "Add search by name, date, and location.", "Debounce or control search where appropriate.", "Handle empty, loading, and error states."],
        ["Position list LWC", "Search behavior", "Navigation", "State tests"],
        ["Filters return correct records.", "Search does not create excessive server calls.", "The table remains usable on smaller screens."],
        ["Where should filtering occur?", "How do you prevent stale results?", "What changes for large data volumes?"],
        "Source project list and search requirements."),
    project_step(14, "Lightning Web Components", "Candidate Position membership component",
        "Show upcoming and past positions and support controlled membership creation.",
        ["Create upcoming and past sections.", "Show only eligible positions.", "Prevent duplicate membership.", "Insert selected junction records.", "Display actionable success and error messages."],
        ["Membership LWC", "Tables", "Creation evidence", "Duplicate tests"],
        ["Duplicate memberships are prevented server-side.", "Only eligible choices are available.", "Past records remain read-only."],
        ["Why is client-side duplicate prevention insufficient?", "How is eligibility enforced?", "How does the component refresh after insert?"],
        "Source project candidate membership requirements."),
    project_step(15, "Flow and LWC", "Screen Flow with membership data table",
        "Add or clear candidate membership through a guided process.",
        ["Create a quick action or screen Flow.", "Offer clear add and clear paths.", "Use a data table for current or eligible positions.", "Insert or delete selected memberships.", "Finish with a clear confirmation."],
        ["Screen Flow", "Data table configuration", "Add and clear tests", "User instructions"],
        ["Both paths are tested.", "The Flow prevents accidental destructive actions.", "Users receive clear confirmation and errors."],
        ["How do you confirm destructive changes?", "How are selections converted to records?", "When would Apex be needed?"],
        "Source project screen Flow requirement."),
    project_step(16, "Experience Cloud", "Experience Cloud foundation",
        "Create the external HR experience and configure access safely.",
        ["Create the site and choose a supported template.", "Create external permission sets or profiles.", "Configure object, field, and record access.", "Add navigation.", "Test as each external user type."],
        ["Experience site", "Access matrix", "Navigation", "External-user tests"],
        ["External users see only intended data.", "Navigation matches their tasks.", "Guest access is minimized and explicitly tested."],
        ["What license assumptions affect the design?", "How do external users receive record access?", "What is exposed to guests?"],
        "Source project Experience Cloud foundation requirement."),
    project_step(17, "Experience Cloud", "Experience design and navigation",
        "Make the external experience understandable, branded, and responsive.",
        ["Create consistent header, footer, labels, and navigation.", "Place useful list, calendar, and activity components.", "Test mobile layouts and keyboard navigation.", "Test guest and authenticated journeys."],
        ["Theme and pages", "Responsive evidence", "Accessibility notes", "Journey tests"],
        ["Primary tasks are easy to find.", "Pages work on desktop and mobile.", "Accessibility and error states are reviewed."],
        ["What is the primary external-user journey?", "How did you test responsiveness?", "How does the design reduce user confusion?"],
        "Source project experience design requirement."),
    project_step(18, "Experience Cloud", "Record-specific components in Experience Cloud",
        "Expose Position and Candidate experiences safely on external pages.",
        ["Enable appropriate Experience Cloud targets.", "Create custom record pages.", "Add record-specific LWCs.", "Configure trusted sites only where needed.", "Verify field and record permissions."],
        ["Experience-enabled LWCs", "Custom pages", "CSP evidence", "Permission tests"],
        ["Components work for intended external users.", "No unnecessary data is exposed.", "Trusted-site configuration is minimal."],
        ["How does the component obtain record context?", "What security checks still apply to Apex?", "Why is each CSP entry required?"],
        "Source project Experience Cloud component requirement."),
    project_step(19, "Service Cloud", "Email-to-Case and follow-up notification",
        "Capture service emails as Cases and alert owners when customers reply.",
        ["Configure Email-to-Case and forwarding.", "Create a queue and assignment process.", "Verify Email Message threading.", "Create a record-triggered Flow for customer replies.", "Test open, closed, owner, and threading scenarios."],
        ["Email-to-Case setup", "Queue", "Notification Flow", "End-to-end evidence", "Support notes"],
        ["Inbound email creates or threads correctly.", "The correct owner or queue is notified.", "Closed-case and duplicate-notification behavior is defined."],
        ["How is email threading maintained?", "What identifies a customer reply?", "How would support diagnose a failed inbound email?"],
        "Source project Email-to-Case requirement."),
]
